#!/usr/bin/env python3
"""Generate styled HTML doc pages from the per-app Markdown sources.

Every app directory holds an ``app.json`` plus ``PRIVACY.md``, ``TERMS.md`` and
``SUPPORT.md``. Those Markdown files are the single source of truth: they are
served verbatim at e.g. https://www.nexomalabs.com/hundy/PRIVACY.md and are also
rendered here into ``privacy.html`` / ``terms.html`` / ``support.html``, which are
the URLs submitted to App Store Connect.

Also regenerates each app's index page and sitemap.xml.

Usage:  python3 tools/build_docs.py [--check]

Standard library only. No build pipeline, no dependencies.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = "https://www.nexomalabs.com"

# Markdown filename -> (output page, human title, short nav label)
DOC_TYPES = [
    ("PRIVACY.md", "privacy.html", "Privacy Policy", "Privacy"),
    ("TERMS.md", "terms.html", "Terms of Service", "Terms"),
    ("SUPPORT.md", "support.html", "Support", "Support"),
    ("FAQ.md", "faq.html", "FAQ", "FAQ"),
    ("SAFETY.md", "safety.html", "Community Safety", "Safety"),
    ("SUBSCRIPTION.md", "subscription.html", "Subscription Terms", "Subscription"),
    ("DATA-DELETION.md", "data-deletion.html", "Data Deletion", "Data deletion"),
]

# An app must publish at least these; the other DOC_TYPES are optional and are
# rendered only when the Markdown file is present.
REQUIRED_DOCS = ("PRIVACY.md", "TERMS.md")

# Written into every generated page. A file that exists WITHOUT this marker is
# treated as hand-authored and is never overwritten.
GENERATED_MARKER = "<!-- generated by tools/build_docs.py - do not edit -->"

# An app is "themed" when it ships assets/docs.css; its pages then use that
# stylesheet and its own chrome instead of the Nexoma Labs site design.
THEME_CSS = "assets/docs.css"

# An app's brand mark, inlined so it paints before the stylesheet loads.
# Read from <app>/assets/brand.svg; an app without one simply has no mark.
BRAND_FILE = "assets/brand.svg"

# Directories that are part of the site chrome, never app doc folders.
RESERVED_DIRS = {"assets", "tools", ".git", ".github"}


# --------------------------------------------------------------------------
# Markdown rendering
# --------------------------------------------------------------------------

INLINE_CODE = re.compile(r"`([^`]+)`")
BOLD = re.compile(r"\*\*([^*]+)\*\*")
ITALIC = re.compile(r"(?<![*\w])\*([^*\n]+)\*(?!\*)")
# _underscore italics_, only when the underscores hug the whole run of text
# so that snake_case_words are left alone.
ITALIC_US = re.compile(r"(?<![\w_])_([^_\n]+)_(?![\w_])")
LINK = re.compile(r"\[([^\]]+)\]\(([^)\s]+)\)")
# <https://example.com> autolinks, matched after HTML escaping.
AUTOLINK = re.compile(r"&lt;(https?://[^\s&<>]+)&gt;")
# The domain may not end on a dot - that is the sentence's full stop.
AUTO_EMAIL = re.compile(r"(?<![\w@.>\"/])([\w.+-]+@[\w-]+(?:\.[\w-]+)+)(?![\w@.<])")


def render_inline(text: str) -> str:
    """Escape a line of Markdown, then apply the inline formatting we use."""
    out = html.escape(text, quote=False)

    # Stash code spans so their contents are never treated as markup.
    spans: list[str] = []

    def stash_code(match: re.Match) -> str:
        spans.append(f"<code>{match.group(1)}</code>")
        return f"\x00{len(spans) - 1}\x00"

    out = INLINE_CODE.sub(stash_code, out)

    def stash_autolink(match: re.Match) -> str:
        href = match.group(1)
        external = SITE_URL not in href
        rel = ' target="_blank" rel="noreferrer"' if external else ""
        spans.append(f'<a href="{href}"{rel}>{href}</a>')
        return f"\x00{len(spans) - 1}\x00"

    out = AUTOLINK.sub(stash_autolink, out)

    def stash_link(match: re.Match) -> str:
        label, href = match.group(1), match.group(2)
        external = href.startswith("http") and SITE_URL not in href
        rel = ' target="_blank" rel="noreferrer"' if external else ""
        spans.append(f'<a href="{html.escape(href, quote=True)}"{rel}>{label}</a>')
        return f"\x00{len(spans) - 1}\x00"

    out = LINK.sub(stash_link, out)
    out = BOLD.sub(r"<strong>\1</strong>", out)
    out = ITALIC.sub(r"<em>\1</em>", out)
    out = ITALIC_US.sub(r"<em>\1</em>", out)

    def stash_email(match: re.Match) -> str:
        addr = match.group(1)
        spans.append(f'<a href="mailto:{addr}">{addr}</a>')
        return f"\x00{len(spans) - 1}\x00"

    out = AUTO_EMAIL.sub(stash_email, out)
    return re.sub(r"\x00(\d+)\x00", lambda m: spans[int(m.group(1))], out)


def render_table(rows: list[str]) -> str:
    """Render a GitHub-flavoured pipe table (header row + separator + body)."""

    def cells(line: str) -> list[str]:
        return [c.strip() for c in line.strip().strip("|").split("|")]

    head = cells(rows[0])
    body = [cells(r) for r in rows[2:]]
    parts = ['<div class="doc-table-wrap"><table class="doc-table">', "<thead><tr>"]
    parts += [f"<th>{render_inline(c)}</th>" for c in head]
    parts.append("</tr></thead><tbody>")
    for row in body:
        parts.append("<tr>")
        parts += [f"<td>{render_inline(c)}</td>" for c in row]
        parts.append("</tr>")
    parts.append("</tbody></table></div>")
    return "".join(parts)


def markdown_to_html(text: str) -> tuple[str, str | None]:
    """Return (html_body, first_h1_title). Supports the subset we author in."""
    lines = text.replace("\r\n", "\n").split("\n")
    out: list[str] = []
    title: str | None = None
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        if stripped in ("---", "***", "___"):
            out.append("<hr />")
            i += 1
            continue

        heading = re.match(r"^(#{1,4})\s+(.*)$", stripped)
        if heading:
            level = len(heading.group(1))
            content = render_inline(heading.group(2).strip())
            if level == 1 and title is None:
                # Plain text, not HTML: callers escape it once themselves.
                title = html.unescape(re.sub(r"<[^>]+>", "", content))
                i += 1
                continue  # the H1 is rendered by the page template instead
            out.append(f"<h{level}>{content}</h{level}>")
            i += 1
            continue

        # Pipe table: header line followed by a |---|---| separator.
        if (
            stripped.startswith("|")
            and i + 1 < len(lines)
            and re.match(r"^\|[\s:|-]+\|$", lines[i + 1].strip())
        ):
            block = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                block.append(lines[i])
                i += 1
            out.append(render_table(block))
            continue

        if re.match(r"^[-*]\s+", stripped):
            out.append("<ul>")
            while i < len(lines) and re.match(r"^[-*]\s+", lines[i].strip()):
                item = re.sub(r"^[-*]\s+", "", lines[i].strip())
                out.append(f"<li>{render_inline(item)}</li>")
                i += 1
            out.append("</ul>")
            continue

        if re.match(r"^\d+[.)]\s+", stripped):
            out.append("<ol>")
            while i < len(lines) and re.match(r"^\d+[.)]\s+", lines[i].strip()):
                item = re.sub(r"^\d+[.)]\s+", "", lines[i].strip())
                out.append(f"<li>{render_inline(item)}</li>")
                i += 1
            out.append("</ol>")
            continue

        if stripped.startswith(">"):
            quote = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                quote.append(re.sub(r"^>\s?", "", lines[i].strip()))
                i += 1
            out.append(f"<blockquote>{render_inline(' '.join(quote))}</blockquote>")
            continue

        # Paragraph: consume until a blank line or the start of another block.
        para = []
        while i < len(lines) and lines[i].strip():
            candidate = lines[i].strip()
            if para and (
                candidate.startswith("#")
                or candidate.startswith(">")
                or candidate.startswith("|")
                or re.match(r"^[-*]\s+", candidate)
                or re.match(r"^\d+[.)]\s+", candidate)
                or candidate in ("---", "***", "___")
            ):
                break
            para.append(candidate)
            i += 1
        out.append(f"<p>{render_inline(' '.join(para))}</p>")

    return "\n".join(out), title


# --------------------------------------------------------------------------
# Page templates
# --------------------------------------------------------------------------


def head(
    app: dict, title: str, description: str, canonical: str, current: str = ""
) -> str:
    """<head> plus the site header, in the app's theme when it has one."""
    nav_links = app["nav_links_for"](current) if app["themed"] else ""
    # Only advertise a social card the app actually ships.
    if (app["path"] / "assets" / "og.png").exists():
        card = f"{SITE_URL}/{app['slug']}/assets/og.png"
        og_image = (
            f'  <meta property="og:image" content="{card}" />\n'
            f'  <meta name="twitter:card" content="summary_large_image" />\n'
            f'  <meta name="twitter:image" content="{card}" />\n'
        )
    else:
        og_image = ""
    if app["themed"]:
        return f"""<!DOCTYPE html>
<html lang="en">
{GENERATED_MARKER}
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
  <title>{html.escape(title)}</title>
  <meta name="description" content="{html.escape(description, quote=True)}" />
  <meta name="author" content="Nexoma Labs LLC" />
  <meta name="robots" content="index,follow" />
  <meta name="theme-color" content="#07090B" />
  <meta property="og:title" content="{html.escape(title, quote=True)}" />
  <meta property="og:description" content="{html.escape(description, quote=True)}" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="{canonical}" />
{og_image}  <link rel="canonical" href="{canonical}" />
  <link rel="icon" href="assets/favicon.svg" type="image/svg+xml" />
  <link rel="stylesheet" href="assets/docs.css" />
</head>
<body>
  <header class="nav">
    <nav class="shell nav-in" aria-label="Primary">
      <a class="brand" href="./" aria-label="{html.escape(app['short_name'], quote=True)} - home">
        {app['brand_mark']}
        {html.escape(app['short_name'])}
      </a>
      <ul class="nav-links">
{nav_links}
      </ul>
      <a class="btn btn-ghost btn-sm" href="./">Back to {html.escape(app['short_name'])}</a>
    </nav>
  </header>
"""

    a = "../"
    return f"""<!DOCTYPE html>
<html lang="en">
{GENERATED_MARKER}
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{html.escape(title)}</title>
  <meta name="description" content="{html.escape(description, quote=True)}" />
  <meta name="author" content="Nexoma Labs LLC" />
  <meta name="robots" content="index,follow" />
  <meta property="og:title" content="{html.escape(title, quote=True)}" />
  <meta property="og:description" content="{html.escape(description, quote=True)}" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="{canonical}" />
  <meta property="og:image" content="{SITE_URL}/assets/banner.png" />
  <link rel="canonical" href="{canonical}" />
  <link rel="icon" type="image/svg+xml" href="{a}assets/favicon.svg" />
  <link rel="stylesheet" href="{a}assets/style.css" />
  <script defer src="{a}assets/main.js"></script>
</head>
<body>
  <header class="site-header">
    <div class="container nav">
      <a class="brand" href="{a}index.html">
        <img src="{a}assets/Nexoma-logo.png" alt="Nexoma Labs logo" />
        <span>NEXOMA LABS</span>
      </a>
      <nav class="site-menu doc-menu" aria-label="Primary">
        <a href="{a}index.html">Home</a>
        <a href="{a}index.html#contact">Contact</a>
      </nav>
      <div class="nav-actions">
        <button class="theme-toggle" type="button" aria-label="Switch color theme">Light Mode</button>
      </div>
    </div>
  </header>
"""


def footer(app: dict) -> str:
    if app["themed"]:
        return f"""
  <footer class="foot">
    <div class="shell">
      <div class="foot-in">
        <div>
          <a class="brand" href="./" style="margin:0">
            {app['brand_mark']}
            {html.escape(app['short_name'])}
          </a>
          <p class="blurb">{html.escape(app['tagline'])}</p>
        </div>
        <div>
          <h4>Documents</h4>
          <ul>
{app['footer_docs']}
          </ul>
        </div>
        <div>
          <h4>Contact</h4>
          <ul>
            <li><a href="mailto:{app['support_email']}">{app['support_email']}</a></li>
            <li><a href="{SITE_URL}">nexomalabs.com</a></li>
          </ul>
        </div>
      </div>
      <div class="foot-btm">
        <span>&copy; {date.today().year} Nexoma Labs LLC. All rights reserved.</span>
        <span>{html.escape(app.get('footer_note', ''))}</span>
      </div>
    </div>
  </footer>
</body>
</html>
"""

    a = "../"
    return f"""
  <footer class="site-footer">
    <div class="container footer-row">
      <div>
        <strong>Nexoma Labs LLC</strong>
        <p>Engineering Intelligent Software.<br />Building the Future.</p>
        <p>&copy; {date.today().year} Nexoma Labs LLC. All Rights Reserved.</p>
      </div>
      <div class="contact-links">
        <a href="{a}index.html">Home</a>
        <a href="https://github.com/NexomaLabs" target="_blank" rel="noreferrer">GitHub</a>
      </div>
    </div>
  </footer>
</body>
</html>
"""


def doc_page(
    app: dict,
    slug: str,
    doc_title: str,
    source: str,
    body: str,
    siblings_present: list,
) -> str:
    canonical = f"{SITE_URL}/{app['slug']}/{slug.replace('.html', '')}"
    name = app["name"]
    description = f"{doc_title} for {name}, a Nexoma Labs LLC application."
    email = app["support_email"]

    siblings = []
    for out, label in siblings_present:
        if out == slug:
            continue
        siblings.append(
            f'<a class="btn btn-secondary btn-sm" href="{out.replace(".html", "")}">{label}</a>'
        )
    siblings.append(
        f'<a class="btn btn-secondary btn-sm" href="{source}">Raw Markdown</a>'
    )

    if app["themed"]:
        breadcrumb = (
            f'<a href="./">{html.escape(name)}</a> <span>/</span> '
            f"<span>{html.escape(doc_title)}</span>"
        )
    else:
        breadcrumb = (
            '<a href="../index.html">Nexoma Labs</a> <span>/</span> '
            f'<a href="./">{html.escape(name)}</a>'
        )

    # If the document states its own date, do not print a second, conflicting one.
    states_own_date = re.search(
        r"last updated|effective date", body[:600], re.IGNORECASE
    )
    date_line = (
        ""
        if states_own_date
        else f"""      <p class="doc-dates">
        Effective {html.escape(app['effective_date'])}
        &middot; Last updated {html.escape(app['updated_date'])}
      </p>"""
    )

    return (
        head(app, f"{doc_title} | {name}", description, canonical, slug)
        + f"""
  <main class="doc-main">
    <article class="doc{'' if app["themed"] else ' container'}">
      <p class="doc-breadcrumb">{breadcrumb}</p>
      <p class="eyebrow">{html.escape(name)}</p>
      <h1>{html.escape(doc_title)}</h1>
{date_line}
      <hr class="doc-rule" />

      <div class="doc-body">
{body}
      </div>

      <aside class="doc-contact">
        <h2>Questions about this document?</h2>
        <p>
          Contact Nexoma Labs LLC at <a href="mailto:{email}">{email}</a>.
        </p>
      </aside>

      <nav class="doc-siblings" aria-label="Related documents">
        {' '.join(siblings)}
      </nav>
    </article>
  </main>
"""
        + footer(app)
    )


def app_index(app: dict) -> str:
    canonical = f"{SITE_URL}/{app['slug']}/"
    name = app["name"]
    cards = []
    for src, out, full in app["present_docs"]:
        cards.append(
            f"""        <article class="doc-card">
          <h3><a href="{out.replace('.html', '')}">{full}</a></h3>
          <p>{html.escape(DOC_BLURBS[src])}</p>
          <p class="doc-card-raw"><a href="{src}">{src}</a></p>
        </article>"""
        )
    return (
        head(
            app,
            f"Documents | {name}",
            f"Privacy policy, terms and support information for {name} by Nexoma Labs LLC.",
            canonical,
        )
        + f"""
  <main class="doc-main">
    <section class="doc{'' if app["themed"] else ' container'}">
      <p class="doc-breadcrumb">
        <a href="{'./' if app['themed'] else '../index.html'}">{html.escape(app['name']) if app['themed'] else 'Nexoma Labs'}</a>
      </p>
      <p class="eyebrow">{html.escape(app['category'])}</p>
      <h1>{html.escape(name)}</h1>
      <p class="lead">{html.escape(app['tagline'])}</p>
      <hr class="doc-rule" />
      <div class="doc-card-grid">
{chr(10).join(cards)}
      </div>
      <aside class="doc-contact">
        <h2>Contact</h2>
        <p>Support for {html.escape(name)}: <a href="mailto:{app['support_email']}">{app['support_email']}</a></p>
      </aside>
    </section>
  </main>
"""
        + footer(app)
    )


DOC_BLURBS = {
    "PRIVACY.md": "What data the app collects, how it is used, and how to have it deleted.",
    "TERMS.md": "The licence and rules that govern your use of the app.",
    "SUPPORT.md": "How to reach us, report a problem, or request a feature.",
    "FAQ.md": "Answers to the questions people ask most often.",
    "SAFETY.md": "Community rules and how to stay safe when meeting other users.",
    "SUBSCRIPTION.md": "What a subscription includes, and how to cancel it.",
    "DATA-DELETION.md": "How to delete your account and everything attached to it.",
}


def sitemap(apps: list[dict]) -> str:
    urls = [(f"{SITE_URL}/", "weekly", "1.0")]
    for app in apps:
        urls.append((f"{SITE_URL}/{app['slug']}/", "monthly", "0.6"))
        for src, out, full in app["present_docs"]:
            urls.append(
                (f"{SITE_URL}/{app['slug']}/{out.replace('.html', '')}", "monthly", "0.5")
            )
    body = "\n".join(
        f"  <url>\n    <loc>{loc}</loc>\n    <changefreq>{freq}</changefreq>\n"
        f"    <priority>{pri}</priority>\n  </url>"
        for loc, freq, pri in urls
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"{GENERATED_MARKER}\n"
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{body}\n</urlset>\n"
    )


# --------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------


REQUIRED_KEYS = [
    "name",
    "category",
    "tagline",
    "support_email",
    "effective_date",
    "updated_date",
]


class ManifestError(Exception):
    """An app.json is missing, malformed, or incomplete."""


def discover_apps() -> list[dict]:
    apps = []
    for path in sorted(ROOT.iterdir()):
        if not path.is_dir() or path.name.startswith(".") or path.name in RESERVED_DIRS:
            continue
        manifest = path / "app.json"
        if not manifest.exists():
            continue

        rel = manifest.relative_to(ROOT)
        try:
            app = json.loads(manifest.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ManifestError(f"{rel} is not valid JSON: {exc}") from None
        if not isinstance(app, dict):
            raise ManifestError(f"{rel} must contain a JSON object.")

        missing = [k for k in REQUIRED_KEYS if not str(app.get(k, "")).strip()]
        if missing:
            raise ManifestError(
                f"{rel} is missing required key(s): {', '.join(missing)}\n"
                f"  Required: {', '.join(REQUIRED_KEYS)}"
            )

        app["slug"] = path.name
        app["path"] = path
        app["short_name"] = app.get("short_name") or app["name"]
        app["themed"] = (path / THEME_CSS).exists()
        mark = path / BRAND_FILE
        if mark.exists():
            svg = mark.read_text(encoding="utf-8")
            svg = re.sub(r"<\?xml[^>]*\?>", "", svg).strip()
            # Strip width/height from the ROOT <svg> tag only, so CSS sizes
            # the mark. Child elements keep theirs - removing those would
            # silently erase parts of the drawing.
            def _strip_root(m: re.Match) -> str:
                return re.sub(r'\s+(width|height)="[^"]*"', "", m.group(0))

            svg = re.sub(r"<svg\b[^>]*>", _strip_root, svg, count=1)
            app["brand_mark"] = re.sub(r"\s*\n\s*", " ", svg)
        else:
            app["brand_mark"] = ""
        apps.append(app)
    return apps


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated files are out of date instead of writing them",
    )
    args = parser.parse_args()

    try:
        apps = discover_apps()
    except ManifestError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if not apps:
        print("No app directories found (each needs an app.json).", file=sys.stderr)
        return 1

    written: list[Path] = []
    stale: list[Path] = []
    skipped: list[Path] = []

    def emit(target: Path, content: str) -> None:
        current = target.read_text(encoding="utf-8") if target.exists() else None

        # Never overwrite a page someone wrote by hand. Generated pages carry a
        # marker; anything else that already exists is left exactly as it is.
        if current is not None and GENERATED_MARKER not in current:
            skipped.append(target)
            return

        if current == content:
            return
        if args.check:
            stale.append(target)
            return
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(target)

    for app in apps:
        # Parse every document this app actually ships, first, so each page can
        # link to its siblings by their real titles.
        parsed = []
        for source, out_name, default_title, short in DOC_TYPES:
            md_path = app["path"] / source
            if not md_path.exists():
                if source in REQUIRED_DOCS:
                    print(
                        f"error: {md_path.relative_to(ROOT)} is required but missing.",
                        file=sys.stderr,
                    )
                    return 1
                continue
            body, own_title = markdown_to_html(md_path.read_text(encoding="utf-8"))
            # A document's own H1 wins over the generic label.
            parsed.append((source, out_name, own_title or default_title, body, short))

        app["present_docs"] = [(s, o, title) for s, o, title, _, _ in parsed]
        siblings_present = [(o, title) for _, o, title, _, _ in parsed]
        app["nav_links_for"] = lambda current, docs=parsed: "\n".join(
            '        <li><a href="{}"{}>{}</a></li>'.format(
                o.replace(".html", ""),
                ' aria-current="page"' if o == current else "",
                html.escape(short),
            )
            for _, o, _t, _b, short in docs
        )
        app["footer_docs"] = "\n".join(
            f'            <li><a href="{o.replace(".html", "")}">{html.escape(title)}</a></li>'
            for _, o, title, _b, _s in parsed
        )

        for source, out_name, doc_title, body, _short in parsed:
            emit(
                app["path"] / out_name,
                doc_page(app, out_name, doc_title, source, body, siblings_present),
            )
        emit(app["path"] / "index.html", app_index(app))

    emit(ROOT / "sitemap.xml", sitemap(apps))

    if args.check:
        for path in skipped:
            print(f"kept  {path.relative_to(ROOT)} (hand-authored, not overwritten)")
        if stale:
            for path in stale:
                print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
            print("\nRun: python3 tools/build_docs.py", file=sys.stderr)
            return 1
        print(f"All generated files are up to date ({len(apps)} apps).")
        return 0

    for path in written:
        print(f"wrote {path.relative_to(ROOT)}")
    for path in skipped:
        print(f"kept  {path.relative_to(ROOT)} (hand-authored, not overwritten)")
    print(f"\n{len(written)} file(s) written for {len(apps)} app(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
